// Generated by Wrangler on Tue Oct 08 2024 01:38:23 GMT+0900 (Korean Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	WHICH_ENV: "development";
}
